/* eslint-disable */
declare module '*.svg'
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.bmp'
declare module '*.tiff'

declare module 'butterfly-dag/plugins/panel/dist'
declare module '@kangc/v-md-editor'
declare module 'vue-grid-layout'
declare module 'crypto-js'
declare module '@logicflow/core'
declare module '*.js'